### ISSUE TITLE
A minor typo in code

### ISSUE THREAD

**Issue by noob-ja** [ouyangzhibo/Image_Foveation_Python#1]
at line 32
`for j in xrange(i):`

should be 
`for j in range(i):`

**Comment by ouyangzhibo** [comment]
No, it's not. If you are using Python 3.x, yes, you are right, you should change it to `range()`; If you are using Python 2.x, then keep it as it is.

PS: `xrange()` in Python 2.x is replaced by `range()` in Python 3.x.
